service-url:
  defaultZone: http://localhost:8761/eureka/
server:
  port: 9999
spring:
  cloud:
    client:
      ipAddress: 192.168.0.193
  application:
    name: web-portal
eureka:
  instance:
    prefer-id: ${spring.cloud.client.ipAddress}:${server.port}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
#feign:
#  hystrix:
#    enabled: true

