service-url:
  defaultZone: http://localhost:8761/eureka/
server:
  port: 13000
spring:
  cloud:
    client:
      ipAddress: 192.168.0.193
  application:
    name: api-gateway-zuul
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    member-service:
      path: /myServerMember/**
      serviceId: service-member
    order-service:
      path: /myServerOrder/**
      serviceId: service-order
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
eureka:
  instance:
    prefer-id: ${spring.cloud.client.ipAddress}:${server.port}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
#    status-page-url: http://localhost:13000/swagger-ui.html